version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18

  build:
    commands:
      - echo "Installing dependencies..."
      - npm install
      - echo "Zipping lambda code..."
      - rm -f lambda.zip
      - zip -r lambda.zip index.js node_modules/ package.json package-lock.json
      - echo "Verifying lambda.zip exists..."
      - ls -lh lambda.zip
      - echo "Uploading to S3: artifact-bucket-e5c7378d"
      - aws s3 cp lambda.zip s3://artifact-bucket-e5c7378d/lambda.zip
      - echo "Updating Lambda function..."
      - aws lambda update-function-code --function-name "example_lambda" --s3-bucket artifact-bucket-e5c7378d" --s3-key lambda.zip
