version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
  build:
    commands:
      - zip -r function.zip index.js
      - aws s3 cp function.zip s3://$S3_BUCKET/lambda.zip

artifacts:
  files:
    - function.zip
