{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": [
        "s3:PutObject",
        "lambda:UpdateFunctionCode"
      ],
      "Resource": [
        "arn:aws:s3:::lambda-function-vishal/*",
        "arn:aws:lambda:us-east-1:975050191688:function:HelloWorldFunction"
      ]
    }
  ]
}
