version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
  build:
    commands:
      - echo "Zipping lambda code"
      - ls -la
      - cd lambda
      - zip -r ../lambda.zip .
      - cd ..
      - echo "Uploading to S3..."
      - aws s3 cp lambda.zip s3://artifact-bucket-2cf3b8bd/lambda.zip
      - echo "Updating Lambda function"
      - aws lambda update-function-code --function-name $LAMBDA_FUNCTION_NAME --s3-bucket artifact-bucket-2cf3b8bd --s3-key lambda.zip
